# Default application configuration that all configurations inherit from.
linters:
    # Prefer border: 0 over border: none.
    BorderZero:
        enabled: true

    # Prefer hexadecimal color codes over color keywords.
    ColorKeyword:
        enabled: false

    # Prefer // comments over /* ... */
    Comment:
        enabled: false

    # Write @extend statements first in rule sets,
    # followed by property declarations and then other nested rule sets.
    DeclarationOrder:
        enabled: true

    # Separate rule, function, and mixin declarations with empty lines.
    EmptyLineBetweenBlocks:
        enabled: true
        ignore_single_line_blocks: true

    # Prefer the shortest possible form for hexadecimal color codes.
    HexFormat:
        enabled: true

    # Don't combine additional selectors with an ID selector.
    IdWithExtraneousSelector:
        enabled: true

    # Use two spaces per indentation level. No hard tabs.
    Indentation:
        enabled: true
        width: 4

    # Don't write leading zeros for numeric values with a decimal point.
    LeadingZero:
        enabled: false

    # Reports when you define the same selector twice in a single sheet.
    MergeableSelector:
        enabled: true
        force_nesting: true

    # Functions, mixins, and variables should be declared with
    # all lowercase letters and hyphens instead of underscores.
    NameFormat:
        enabled: true
        convention: hyphenated_lowercase # or 'BEM', or a regex pattern

    # Always use placeholder selectors in @extend.
    PlaceholderInExtend:
        enabled: false

    # Sort properties in a strict order.
    PropertySortOrder:
        enabled: false

    # Reports when you use an unknown
    # CSS property (ignoring vendor-prefixed properties).
    PropertySpelling:
        enabled: true
        extra_properties: []

    # Don't write selectors with a depth of applicability greater than 4.
    SelectorDepth:
        enabled: true
        max_depth: 4

    # Prefer the shortest shorthand form
    # possible for properties that support it.
    Shorthand:
        enabled: true

    # Split selectors onto separate lines after each comma.
    SingleLinePerSelector:
        enabled: true

    # Commas in lists should be followed by a space.
    SpaceAfterComma:
        enabled: true

    # Properties should be formatted with a single space separating
    # the colon from the property's value.
    SpaceAfterPropertyColon:
        enabled: true
        allow_extra_spaces: true

    # Properties should be formatted with no space between
    # the name and the colon.
    SpaceAfterPropertyName:
        enabled: true

    # Opening braces should be preceded by a single space.
    SpaceBeforeBrace:
        enabled: true
        allow_single_line_padding: true

    # Parentheses should not be padded with spaces.
    SpaceBetweenParens:
        enabled: true
        spaces: 0

    # String literals should be written with single quotes unless
    # using double quotes would save on escape characters.
    StringQuotes:
        enabled: true
        style: double_quotes # or double_quotes

    # Property values should always end with a semicolon.
    TrailingSemicolonAfterPropertyValue:
        enabled: true

    # Numeric values should not contain unnecessary fractional portions.
    UnnecessaryMantissa:
        enabled: true

    # URLs should not contain protocols or domain names.
    UrlFormat:
        enabled: true

    # URLs should always be enclosed within quotes.
    UrlQuotes:
        enabled: true

    # Omit length units on zero values.
    ZeroUnit:
        enabled: true

    # scss-lint includes a set of linters for codebases
    # which use the Compass framework.
    Compass::*:
        enabled: false
